#!/usr/bin/env bash
#
# Bootstrap the single-interface Zammad PoC:
#   1. Clone the official zammad-docker-compose stack (kept out of this repo).
#   2. Generate .env with a random DB password and the bind address of your
#      choice (VPN IP, LAN IP, or 127.0.0.1).
#
# Idempotent — safe to re-run. An existing .env is never overwritten.
#
# Pass the address explicitly (Tailscale autodetection kicks in if you don't):
#   BIND_IP=192.168.1.20 ZAMMAD_HOST=192.168.1.20 ZAMMAD_UI_PORT=8081 ./setup.sh
set -euo pipefail
cd "$(dirname "$0")"

UPSTREAM_REPO="https://github.com/zammad/zammad-docker-compose.git"
UPSTREAM_DIR="zammad-docker-compose"

if [ ! -d "$UPSTREAM_DIR" ]; then
  echo "==> Cloning the official Zammad compose stack…"
  git clone --depth 1 "$UPSTREAM_REPO" "$UPSTREAM_DIR"
else
  echo "==> $UPSTREAM_DIR already present (update with: git -C $UPSTREAM_DIR pull)"
fi

if [ -f .env ]; then
  echo "==> .env already exists — leaving it untouched."
else
  # Bind address: defaults to this machine's Tailscale IPv4.
  BIND_IP="${BIND_IP:-$(tailscale ip -4 2>/dev/null | head -n1 || true)}"
  if [ -z "$BIND_IP" ]; then
    read -rp "Bind address (VPN IP, LAN IP, or 127.0.0.1): " BIND_IP
  fi

  # Hostname for browser URLs: defaults to the Tailscale MagicDNS name.
  ZAMMAD_HOST="${ZAMMAD_HOST:-$(tailscale status --json 2>/dev/null | sed -n 's/.*"DNSName": *"\([^"]*\)\.".*/\1/p' | head -n1 || true)}"
  ZAMMAD_HOST="${ZAMMAD_HOST:-$BIND_IP}"

  ZAMMAD_UI_PORT="${ZAMMAD_UI_PORT:-8081}"
  TZ_VALUE="${TZ:-$(cat /etc/timezone 2>/dev/null || timedatectl show -p Timezone --value 2>/dev/null || echo UTC)}"

  umask 077
  cat > .env <<EOF
# Generated by setup.sh — contains a password, do not commit.

# Official upstream stack + local override (single-interface binding).
# The built-in backup service is disabled for this evaluation setup.
COMPOSE_FILE=${UPSTREAM_DIR}/docker-compose.yml:${UPSTREAM_DIR}/scenarios/disable-backup-service.yml:docker-compose.override.yml
COMPOSE_PROJECT_NAME=zammad

# Publish the web UI on this address only (VPN IP, LAN IP, or 127.0.0.1).
BIND_IP=${BIND_IP}
ZAMMAD_UI_PORT=${ZAMMAD_UI_PORT}

# Seeded into Zammad on FIRST boot only (Settings fqdn / http_type).
# Changing them later requires: Setting.set(...) in a rails console.
ZAMMAD_FQDN=${ZAMMAD_HOST}:${ZAMMAD_UI_PORT}
ZAMMAD_HTTP_TYPE=http

TZ=${TZ_VALUE}
POSTGRES_PASS=$(openssl rand -hex 16)
EOF
  echo "==> Wrote .env (binding ${BIND_IP}:${ZAMMAD_UI_PORT})"
  echo
  echo "Next steps:"
  echo "  docker compose up -d"
  echo "  open http://${ZAMMAD_HOST}:${ZAMMAD_UI_PORT} and walk through the setup wizard"
fi
